/*
 * roomservice
 *
 * An implementation of joinable rooms
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// RoomApiService is a service that implents the logic for the RoomApiServicer
// This service should implement the business logic for every endpoint for the RoomApi API. 
// Include any external packages or services that will be required by this service.
type RoomApiService struct {
}

// NewRoomApiService creates a default api service
func NewRoomApiService() RoomApiServicer {
	return &RoomApiService{}
}

// AddRoom - Create a new room
func (s *RoomApiService) AddRoom() (interface{}, error) {
	// TODO - update AddRoom with the required logic for this service method.
	// Add api_room_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'AddRoom' not implemented")
}
