/*
 * roomservice
 *
 * An implementation of joinable rooms
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Room - A room
type Room struct {

	Id int64 `json:"id,omitempty"`

	Code string `json:"code,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
