/*
 * roomservice
 *
 * An implementation of joinable rooms
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package galactuslib

import (
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/go-pg/pg/v10"
)

// RoomApiService is a service that implents the logic for the RoomApiServicer
// This service should implement the business logic for every endpoint for the RoomApi API.
// Include any external packages or services that will be required by this service.
type RoomApiService struct {
	// rooms is a mapping from the room id to the actual Room object
	rooms           *map[string]Room
	seededGenerator *rand.Rand
	db              *pg.DB
}

const defaultSeed int64 = 42
const maxCode int64 = 9999

// NewRoomApiService creates a default api service
func NewRoomApiService(mapReference *map[string]Room, dbReference *pg.DB) RoomApiServicer {
	return &RoomApiService{
		rooms:           mapReference,
		seededGenerator: rand.New(rand.NewSource(defaultSeed)),
		db:              dbReference,
	}
}

// AddRoom - Create a new room
func (s *RoomApiService) AddRoom() (interface{}, error) {
	// get the room using the map
	if s.rooms == nil {
		return nil, errors.New("map reference is nil, there is something wrong with initialization")
	}
	roomMap := *s.rooms
	roomNum := s.seededGenerator.Int63n(maxCode + 1)
	roomCode := fmt.Sprintf("%04d", roomNum)

	// make sure we create a new room
	for _, ok := roomMap[roomCode]; ok; _, ok = roomMap[roomCode] {
		roomNum = s.seededGenerator.Int63n(maxCode + 1)
		roomCode = fmt.Sprintf("%04d", roomNum)
	}

	createdAt := time.Now()

	// In memory store.
	roomMap[roomCode] = Room{
		Id:        roomNum,
		Code:      roomCode,
		CreatedAt: createdAt,
	}

	// DB Store for persistence.
	_, err := s.db.Model(&Room{
		Id:        roomNum,
		Code:      roomCode,
		CreatedAt: createdAt,
	}).Insert()
	if err != nil {
		panic(err)
	}

	return roomMap[roomCode], nil
}
