/*
 * roomservice
 *
 * An implementation of joinable rooms
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package galactuslib

// Postgres
const pq_user string = "postgres"
const pq_pass string = "postgres"
const pq_host string = "postgres_host"
const pq_port string = "5432"
const pq_dbname string = "postgres"
