/*
 * roomservice
 *
 * An implementation of joinable rooms
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package galactuslib

type CodeAndDate struct {
	Code string `json:"code,omitempty"`

	Date string `json:"date,omitempty"`
}
