openapi: 3.0.0
info:
  contact:
    email: decline@umass.edu
    name: Dan Cline
  description: An implementation of joinable rooms
  license:
    name: MIT
  title: roomservice
  version: 0.0.1
servers:
- url: http://galactus.player/v1
paths:
  /gencode:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeAndDate'
          description: Room Code and Date.
      summary: Return a fresh room code and date of creation.
  /room/{id}:
    get:
      parameters:
      - description: Joining Room ID.
        explode: false
        in: path
        name: id
        required: false
        schema:
          $ref: '#/components/schemas/Code'
        style: simple
      responses:
        200:
          description: OK
        404:
          description: Room Not Found
components:
  schemas:
    Code:
      type: string
    CodeAndDate:
      example:
        date: 2017-07-21T17:32:28Z
      properties:
        code:
          type: string
        date:
          type: string
      type: object
    Name:
      type: string
